services:
    java:
      container_name: gaj-service
      image: gaj-service:0.1
      ports:
        - 8080:8080
        - 8083:8083
      volumes:
        - ./gaj-server-main:/gaj-server-main
        - ./conf/compilar.sh:/usr/local/bin/compilar.sh
        #- ./keys/server.xml:/opt/tomcat/conf/server.xml
        #- ./keys/sqlhosts:/etc/sqlhosts
        - ./conf/m2-settings.xml:/root/.m2/settings.xml
        - ./conf/python-scripts:/root/python
    db:
        image: postgres:17
        container_name: gajdb
        restart: always
        environment:
          POSTGRES_DB: gaj
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pass123
        volumes:
          #- ./m_gaj.27-03-23.esquema.sql:/docker-entrypoint-initdb.d/init-db.sql
          - ./m_gaj.27-03-23.esquema.sql:/esquema.sql
        ports:
          - "5432:5432"